### ISSUE TITLE
Youtube urls don't work

### ISSUE THREAD

**Issue by hkmsadek** [e-oj/grabity#7]
It works nicely for all other urls but for youtube, it doesn't work. Any reason why? thanks

**Comment by e-oj** [comment]
Sorry for the late response, I've been very busy lately. Youtube urls do not use the open graph protocol. You would have to make some calls to the [Youtube API](https://developers.google.com/youtube/v3/) for that.

**Comment by e-oj** [comment]
Feel free to reopen this issue if you have any related questions.
